### PR TITLE
Separated imports by notebooks

### PR DESCRIPTION
**Pull request by manojneuro**
Addresses review #12

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
Hi @manojneuro,

Sorry for the delay - I was never assigned as a reviewer so I didn't get an alert that this PR is ready for review.

**Review by mathieuboudreau — CHANGES_REQUESTED** [review]
NiLearn is throwing an error related to sklearn - either there is an incompatibility between the two softwares we have (they likely install latest instead of fixed versions), or a problem with the NiLearn version.

See screenshot: 

Capture d’écran 2020-06-16 à 14 14 50

Tested on this MyBinder link: https://mybinder.org/v2/gh/manojneuro/brainiak-tutorials/update-nb-0

**Comment by mathieuboudreau** [comment]
Related online: https://github.com/shimaokasonse/NFGEC/issues/5

We don't specify a specific sklearn version in the requirements.txt file, so we might need to to be compatible with nilearn (which might be downloading the latest version).

**Comment by mathieuboudreau** [comment]
@manojneuro Adding this line resolved the issue:

https://github.com/mathieuboudreau/brainiak-tutorials/commit/cd6b87f4cdddb3f48ed83ec466d4943eaf109d08

Do that in your branch and this PR will be ready for merging

**Comment by manojneuro** [comment]
@mathieuboudreau I have made the changes to the environment file. Thanks

**Review by mathieuboudreau — APPROVED** [review]
Resolved, thank you!

**Pull request merged**
