### PR TITLE
Add version numbers to requirements.txt

### PR DESCRIPTION
**Pull request by mihaic**
See issue #11.

### CODE REVIEW

**Comment by mihaic** [comment]
The versions are coming from the BrainIAK Docker image:
https://hub.docker.com/layers/brainiak/brainiak/latest/images/sha256-c4ebd1106b9fe349a9f1d362a9b9358f5c7024904ae0a96a69ee22bf72c2e002

**Review by ltetrel — COMMENTED** [review]
Do you think it can be possible to add all the `apt.txt` dependencies inside this environment.yml ?
I am not sure about the difference between including the linux dependencies inside the environment.yml or the apt.txt

**Review by ltetrel — COMMENTED** [review]
Did you tested this new environment by trying to build the notebook here https://binder.conp.cloud/, before we merge it ?

**Comment by mihaic** [comment]
I had only tested on my machine with repo2docker. But now I tried it on binder.conp.cloud the first couple of notebooks seem fine:
https://binder.conp.cloud/v2/gh/mihaic/tutorials/requirements-versions

Regarding `apt.txt`, as far as I understand from looking at the upstream repo2docker Python image, a Conda environment is already used with a `requirements.txt` file and no `environment.yml`, so this PR should not introduce changes.

**Comment by ltetrel** [comment]
@mathieuboudreau can you follow up with this one wince you are the reviewer ? After review I think there is no reason to reject this but you can check yourself.

**Comment by mathieuboudreau** [comment]
I will look at this ASAP. I'm flying today so I might not get to it until Monday, but will get it done by then at the latest.

**Comment by mathieuboudreau** [comment]
Looks great & works on my end, I'll merge now!

**Pull request merged**
