### PR TITLE
Update nb02

### PR DESCRIPTION
**Pull request by manojneuro**
Addressed points in the review.
Added description of localizer.

### CODE REVIEW

**Comment by manojneuro** [comment]
This addresses review comments in Issue #14

**Comment by lunebellec** [comment]
LGTM

@mathieuboudreau could you please check that this addresses your feedback?

**Comment by mathieuboudreau** [comment]
I started to try to look into this, however this error that's been reported about the most recent Brainiak release prevents installation in the Docker image: https://github.com/brainiak/brainiak/issues/435

It's odd that they would have setup their pipy wheel to require that flag to be passed to avoid an error; typically well-build pipy wheels don't need such flags in my experience. Not sure how this could be passed on using a requirements.txt file. @emdupre have you ever encountered something like this?

**Comment by mathieuboudreau** [comment]
Actually, it also happens for version 0.9, which should be the version that I tested it on. Not sure why this error is popping up now for me on mybinder/repo2docker and wasn't on neurolibre. I can't test it on neurolibre at the moment due to the site issue.

**Comment by manojneuro** [comment]
@mathieuboudreau: we had some issues installing BrainIAK on NeuroLibre at OHBM. As a workaround we used the Apt.txt file to build binder on NeuroLibre. @ltetrel can provide more details on the binder build. @mihaic can provide more details on the Docker and pipy build for brainiak.

**Comment by mihaic** [comment]
The `--no-use-pep517` Pip flag discussed in https://github.com/brainiak/brainiak/issues/435 is not yet supported in `requirements.txt`, but there is a PR for it, https://github.com/pypa/pip/pull/6447. In the meantime, use Pip <10 as a workaround, as discussed in the BrainIAK issue.
Edit: corrected typo.

**Review by mathieuboudreau — COMMENTED** [review]
@manojneuro The changes done in tutorials/02-data-handling.ipynb have resolved all my issues, and this PR for merging this file. I think however that you accidentally branched out of another branch meant for another PR, resulting in one other file changed in this PR (tutorials/03-classification.ipynb). Could you remove that file from this branch, and then I will approve?

**Comment by manojneuro** [comment]
@mathieuboudreau Thanks for your review. I removed the extra file from the PR. Please take a look.

**Pull request merged**
